version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=ecommerce_db
      - DB_PORT=3306
      - JWT_SECRET=supersecret
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
